language: shell
os: linux
dist: bionic


notifications:
  email:
    on_success: never
    on_failure: always

script:
  - git clone https://github.com/Code-Egg/lsws1clk.git
  - sudo bash -x lsws1clk/lsws1clk.sh -W
