language: shell
os: linux
dist: bionic
if: branch = master

notifications:
  email:
    on_success: always
    on_failure: always

env:
  - APP='W'
  - APP='M'

script:
  - |
    if [ $TRAVIS_BRANCH == "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        git clone https://github.com/Code-Egg/lsws1clk.git
        sudo bash -x lsws1clk/lsws1clk.sh "-$APP"
    fi    
