name: lsws1clk

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        APP: [W]
    steps:
      - uses: actions/checkout@v2
      - name: lsws1clk test
        run: sudo bash -x lsws1clk.sh "-${{matrix.APP}}"
          
